# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colpafs <- function(y, a, ncores = 1L) {
    .Call(`_DER_colpafs`, y, a, ncores)
}

colpafs2 <- function(y, a, ncores = 1L) {
    .Call(`_DER_colpafs2`, y, a, ncores)
}

kde <- function(y, h, ncores = 1L) {
    .Call(`_DER_kde`, y, h, ncores)
}

paf <- function(y, a, ncores = 1L) {
    .Call(`_DER_paf`, y, a, ncores)
}

paf2_parallel <- function(y, a, ncores = 1L) {
    .Call(`_DER_paf2_parallel`, y, a, ncores)
}

paf2 <- function(y, a, ncores = 1L) {
    .Call(`_DER_paf2`, y, a, ncores)
}

pafF_helper <- function(y, a, ncores = 1L) {
    .Call(`_DER_pafF_helper`, y, a, ncores)
}

