# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

paf_fun <- function(y, a, h, ncores = 1L) {
    .Call(`_DER_paf_fun`, y, a, h, ncores)
}

